### ISSUE TITLE
Enable New Rustacean podcast on Spotify

### ISSUE THREAD

**Issue by petertrotman** [chriskrycho/newrustacean.com#109]
Hello,

I use Spotify a lot for podcasts, and I noticed that New Rustacean is not available on there. Spotify simply outsources their aggregation to other podcast aggregators so I don't think there's any arduous process to go through.

Instructions are here: https://artists.spotify.com/faq#how-do-i-get-a-podcast-on-spotify
I notice that New Rustacean is on at least PodBean, the instructions for activation on Spotify through PodBean are here, and look to be basically a single click: http://help.podbean.com/support/solutions/articles/25000014128-how-to-submit-your-podbean-podcast-to-spotify

Cheers,

P

**Comment by chriskrycho** [comment]
Hi @petertrotman, thanks for listening!

This is a request I get fairly often, as you can imagine. Unfortunately, I find Spotify's Terms of Service for artists (including podcasters) onerous – in particular, their section **7. Rights You Grant Us**. (I have basically the same sets of objections to Google Play Podcasts and Stitcher.)

The reality is that Spotify, Google Play Podcasts, and Stitcher have all chosen to rehost podcaster's content in their own silos instead of using the existing open infrastructure on which podcasts are built – RSS feeds on the open web – and I'm simply not interested in encouraging that approach.

I do regret the inconvenience this causes for some listeners (like you!), though! My strong recommendation is to use [Overcast](https://overcast.fm/) (iOS) or [Pocket Casts](https://www.shiftyjelly.com/pocketcasts/) (iOS and Android) – both of them are legitimately excellent podcast players, and both actively support the open web/RSS-based approach to podcasts.

Again, I do apologize for the inconvenience, and thanks for listening!

**Comment by petertrotman** [comment]
Ok, I understand that. I searched the issues beforehand to make sure I wasn't obviously the first person to request it. I guess I'll stick with the browser for desktop use!

Cheers,

P

**Comment by chriskrycho** [comment]
Yep, no worries at all! This is, perhaps surprisingly, the first time anyone has asked via a GH issue! (All previous asks have been via email or Twitter!)
