### ISSUE TITLE
Error in episode 5

### ISSUE THREAD

**Issue by cmlsharp** [chriskrycho/newrustacean.com#7]
In `e005`, you state that variable length array declarations are not allowed in C without malloc. In fact, this was a mandatory feature in C99 (though it was made optional in C11)

**Comment by chriskrycho** [comment]
Thanks, @crossroads1112; great point. I'd forgotten about that, because I've spent so much time over the last few years working in contexts where that C99 change was unsupported. (It's still unsupported for C++ in MSVC++ [as of VS2015](https://msdn.microsoft.com/en-us/library/zb1574zs%28v=vs.140%29.aspx)!)

In any case, I'll add a note to the show notes and mention it on the next episode. Thanks!

(Also, this issue reminded me to tweak my email settings for this repository so I see these kinds of things a bit sooner. Sorry about the delay!)

**Comment by cmlsharp** [comment]
No worries! Keeping track of what the standard vs the various implementations can be difficult. If you're interested, [here](https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html) are the GCC docs on VLAS. It seems to be similar to calling `alloca()`.

**Comment by chriskrycho** [comment]
Corrigenda added in 17c5f8c.
